export { SignUp } from './SignUp/SignUp';
export { PropertyDetail } from './PropertyDetail/PropertyDetail';
export { PropertiesIndex } from './PropertiesIndex/PropertiesIndex';
export { Login } from './Login/Login';
export { Home } from './Home/Home';
export { Profile } from './Profile/Profile';
export { PostSignUp } from './PostSignUp/PostSignUp';
export { ForgotPassword } from './ForgotPassword/ForgotPassword';
export { EditProfile } from './EditProfile/EditProfile';
